language: ruby

services:
  - docker

before_install:
  - docker pull amazoncorretto:11

script:
  - docker run --rm -v $TRAVIS_BUILD_DIR:/source -v artifact_volume:/artifact_volume amazoncorretto:11 -env GPR_USERNAME=$GPR_USERNAME -env GPR_PASSWORD=$GPR_PASSWORD /bin/sh -c "cd /source ; ./gradlew clean build -x test publish"
